name: video-downloader
region: nyc
services:
  - name: backend
    source_dir: backend
    dockerfile_path: Dockerfile
    github:
      branch: main
      deploy_on_push: true
      repo: your-github-username/video-downloader
    http_port: 5000
    instance_size_slug: basic-xxs
    routes:
      - path: /api
    envs:
      - key: FLASK_ENV
        value: production
      - key: CORS_ORIGINS
        value: ${APP_URL}

  - name: frontend
    source_dir: frontend
    dockerfile_path: Dockerfile
    github:
      branch: main
      deploy_on_push: true
      repo: your-github-username/video-downloader
    http_port: 80
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: REACT_APP_API_URL
        value: ${APP_URL}