name: video-downloader
region: nyc
services:
  - name: backend
    source_dir: backend
    dockerfile_path: Dockerfile
    github:
      branch: main
      deploy_on_push: true
      repo: cwhitelam/Twitter-Downloader
    http_port: 5000
    instance_size_slug: basic-xxs
    routes:
      - path: /api
    envs:
      - key: FLASK_ENV
        value: production
      - key: CORS_ORIGINS
        value: ${APP_URL}
    health_check:
      http_path: /api/health
      port: 5000

static_sites:
  - name: frontend
    source_dir: frontend
    build_command: npm run build
    output_dir: build
    github:
      branch: main
      deploy_on_push: true
      repo: cwhitelam/Twitter-Downloader
    routes:
      - path: /
    envs:
      - key: REACT_APP_API_URL
        value: ${APP_URL}