name: "Deploy to DigitalOcean"
on:
  push:
    branches: 
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          
      - name: Deploy to DigitalOcean App Platform
        run: doctl apps update ${{ secrets.APP_ID }} --spec app.yaml
        env:
          APP_ID: ${{ secrets.APP_ID }}